# permissions for end users to edit helidons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helidon-editor-role
rules:
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - helidons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - helidons/status
  verbs:
  - get
