# permissions for end users to view ochacaves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ochacafe-viewer-role
rules:
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves/status
  verbs:
  - get
