# permissions for end users to edit ochacaves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ochacafe-editor-role
rules:
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves/status
  verbs:
  - get
