
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves/finalizers
  verbs:
  - update
- apiGroups:
  - ochacafe.oracle.com
  resources:
  - ochacaves/status
  verbs:
  - get
  - patch
  - update
