
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ochacafe.com.oralce
  resources:
  - helidons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ochacafe.com.oralce
  resources:
  - helidons/finalizers
  verbs:
  - update
- apiGroups:
  - ochacafe.com.oralce
  resources:
  - helidons/status
  verbs:
  - get
  - patch
  - update
